### PR TITLE
Feature/dist

### PR DESCRIPTION
**Pull request by pesterhazy**
Add a `boot` task `bundle` to create offline bundles

Needs some work to become more configurable but is already quite useful

### CODE REVIEW

**Comment by mjmeintjes** [comment]
Thanks for this. I'm planning to do a release this weekend and will merge and test this as part of the release.

**Comment by mjmeintjes** [comment]
Hi. Just looking at this PR now. I'm not an expert at iOS functionality, but wouldn't the change at example/app/ios/SimpleExampleApp/AppDelegate.m cause the development version to not work. If so, might make sense to revert that change and just add to deployment instructions in readme.

**Comment by pesterhazy** [comment]
Good call. I updated AppDelegate.m and added some preliminary docs.

**Comment by pesterhazy** [comment]
And updated to include master

**Pull request merged**
