### PR TITLE
Run example in simulator without xcode

### LINKED ISSUE #14: Run ios sim with single command
With https://github.com/facebook/react-native/pull/5119, it should be possible to build and run an app in the iOS simulator directly, without opening xcode (I think this was supported for android earlier). Might be a nice idea to add support or documentation for this.

### PR DESCRIPTION
**Pull request by pesterhazy**
Adds functionality to run app in iOS simulator and to see logs

Fixes #14 

This relies on code in react-native that didn't make it into the 0.18
release. For this reason, set react-native dependency to a specific commit in
package.json.

The last bit is probably contentious, although so far I haven't seen any issue
with running this dev version of react-native (should be similar to 0.18 in most
regards).

### CODE REVIEW

**Comment by jellea** [comment]
Can confirm this works, just went through this together with @pesterhazy :) Don't forget to `rm -rf example/app/node_modules` and `npm install` again.

**Comment by mjmeintjes** [comment]
Cool. Would it be possible to build something similar to `print-android-log` (https://github.com/mjmeintjes/boot-react-native/blob/master/src/mattsum/boot_react_native.clj#L162) for iOS using the code in `tail-ios-sim`? Maybe a task called `print-ios-log`, and then a `print-log` task that combines the 2.

**Comment by pesterhazy** [comment]
I think that's a great idea, will see what I can do.

There's also react native's `run-android`, which you could have
automatically run after the first compilation (and on iOS, `run-ios`).

**Comment by pesterhazy** [comment]
I've added boot tasks for running in the simulator and for tailing logs (similar to print-android-log). What do you think?

These tasks are only triggered if you run `boot dev --platform ios`. Similarly, you could add a `--platform android` functionality. I've also renamed the task from `fast-build` to `dev` to be more in line with boot standards, but happy to revert this.

**Comment by mjmeintjes** [comment]
Cool - looks good, thanks. With respect to the platform flag - instead, what about having 3 tasks:

`dev` - contains the default tasks (I agree with the rename, by the way)
`android` - contains android specific tasks
`ios` - contains ios specific tasks

Then, user can run `boot dev android` or `boot dev ios`, or even `boot dev android ios`.

**Comment by mjmeintjes** [comment]
I've pushed the changes I made to sourcemap branch.

**Comment by pesterhazy** [comment]
@mjmeintjes, agree that would be nice. One problem is that the `run-in-simulator` task should be run after `rn/after-cljsbuild`.

`print-ios-log` should be fine I think, although it needs the simulator to be started already to be able to find the right log file.

What I could do is just to set the `platform` option in `task-options` in a separate `ios` task.

Anyway the timing of tasks is the main problem. I'm also not 100% clear on how to influence boot's task order and boot-react-native's tasks are already pretty complicated, so maybe you have an idea how to open the sim in a separate task?

**Comment by mjmeintjes** [comment]
It might just be best then to keep the platform parameter as is in your PR. I'll probably just add dev-android and dev-ios tasks that set platform parameter before calling into the dev task. 

I'll merge and run tests on Android.

**Comment by pesterhazy** [comment]
:fireworks:

**Pull request merged**
